#!/usr/bin/with-contenv bash

UMASK_SET=${UMASK_SET:-022}

umask "$UMASK_SET"

cd /app/sonarr/bin || exit

echo "Sleeping a bit, to let hydra and nzbget come up ..."
sleep 60
echo "enough slept, let's go!"

exec \
	s6-setuidgid abc mono --debug NzbDrone.exe \
	-nobrowser -data=/config